services:
    metamodels.filter_register.factory:
        class: MetaModels\FilterRegisterBundle\FilterSetting\RegisterFilterSettingTypeFactory
        arguments:
          - '@event_dispatcher'
          - '@MetaModels\Filter\FilterUrlBuilder'
        tags:
          - { name: metamodels.filter_factory }

    metamodels.filter_register.listener.filter_setting_renderer:
        class: MetaModels\FilterRegisterBundle\EventListener\RegisterFilterSettingTypeRendererListener
        arguments:
          - "@metamodels.filter_setting_factory"
          - "@event_dispatcher"
          - "@metamodels.assets.icon_builder"
          - "@cca.dc-general.scope-matcher"
        tags:
          - {
              name: kernel.event_listener,
              event: 'dc-general.view.contao2backend.model-to-label',
              method: modelToLabel
            }
